#!/bin/bash
# OpenTron CLI Demo Script
# This demonstrates the OpenTron CLI functionality

echo ""
echo "╭────────────────────────────────────────────────────────╮"
echo "│     OpenTron - Personal AI Assistant CLI               │"
echo "│                                                          │"
echo "│  Version 0.1.0 | Local-first | Privacy-focused         │"
echo "╰────────────────────────────────────────────────────────╯"
echo ""

# Show available commands
echo "[Available Commands]"
echo ""
echo "SETUP & CONFIGURATION:"
echo "  tron init                       Initialize OpenTron"
echo "  tron doctor                     System diagnostics"
echo "  tron config show                View configuration"
echo ""
echo "CHAT & QUERIES:"
echo "  tron chat                       Interactive multi-turn chat"
echo "  tron ask \"question\"             Single query"
echo "  tron --voice                    Voice-activated chat"
echo ""
echo "MODELS:"
echo "  tron model list                 List available models"
echo "  tron model pull qwen2.5:7b      Download model"
echo ""
echo "MEMORY & KNOWLEDGE:"
echo "  tron memory list                View memories"
echo "  tron memory search \"topic\"      Search knowledge base"
echo "  tron memory add \"fact\"          Store new memory"
echo ""
echo "AGENTS:"
echo "  tron agent list                 List agents"
echo "  tron agent create --name NAME   Create new agent"
echo "  tron agent run AGENT_ID         Execute agent"
echo ""
echo "TOOLS & WORKFLOWS:"
echo "  tron tool list                  Available tools"
echo "  tron workflow list              Show workflows"
echo "  tron skill list                 Agent skills"
echo ""
echo "INTEGRATIONS:"
echo "  tron vault list                 Stored credentials"
echo "  tron channels list              Channel integrations"
echo ""
echo "DIAGNOSTICS:"
echo "  tron traces list                Execution traces"
echo "  tron learning AGENT_ID          Learning history"
echo ""
echo "─────────────────────────────────────────────────────────"
echo ""
echo "[Feature Highlights]"
echo ""
echo "✅ Voice Activation (macOS, Windows, Linux native APIs)"
echo "✅ Hardware Auto-Detection"
echo "✅ Vision Support (images + screenshots)"
echo "✅ Knowledge Base with Semantic Search"
echo "✅ Persistent Agent Management"
echo "✅ Workflow Composition"
echo "✅ Encrypted Credential Storage"
echo "✅ Real-time Execution Traces"
echo "✅ Learning History Tracking"
echo "✅ Multi-Channel Integration"
echo ""
echo "─────────────────────────────────────────────────────────"
echo ""
echo "[Quick Start]"
echo ""
echo "1. Initialize:"
echo "   $ tron init"
echo ""
echo "2. Start chatting:"
echo "   $ tron chat"
echo "   or use voice mode:"
echo "   $ tron --voice"
echo ""
echo "3. Try a quick query:"
echo "   $ tron ask \"What is machine learning?\""
echo ""
echo "─────────────────────────────────────────────────────────"
echo ""
echo "[Documentation]"
echo ""
echo "📖  DOCUMENTATION_INDEX.md"
echo "📖  QUICK_REFERENCE.md"
echo "📖  COMPLETE_IMPLEMENTATION_GUIDE.md"
echo "📖  COOKBOOK_AND_TROUBLESHOOTING.md"
echo "📖  PROJECT_COMPLETE.md"
echo ""
echo "For more information, see the documentation files in:"
echo "  C:\\Users\\ermis\\Documents\\OpenTron\\java\\opentron-java\\"
echo ""
